name: Shell commands
on: [push]

jobs:
  run-shell-command:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo a string
        run: echo "Hello world"

      - name: Multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l
